name: flutter_responsive_template
description: Package para desenvolvimento de aplicações responsivas (desktop e mobile). 
version: 1.1.6
homepage: https://github.com/lucas9599/flutter_responsive

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"
module:
    androidX: true     

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter  
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+4
  flutter_modular: ^5.0.3
  shared_preferences: ^2.0.18
  select_form_field: ^2.2.0
  enhance_stepper: ^0.1.1
  printing: ^5.11.0
  pdf: ^3.10.0
  file_selector: ^1.0.0
  bitsdojo_window: ^0.1.5
  data_table_2: ^2.3.12
  encrypt: ^5.0.1
  date_field: ^3.0.3
  brasil_fields: ^1.9.1
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.2.19  
  image: ^4.0.17
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  mockito: ^5.2.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "imagens/icon.png"
  image_path_ios: "imagens/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "imagens/icon.png"
  web:
    generate: true
    image_path: "imagens/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "imagens/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  image: imagens/icon.png
  color: "#fce5de" 
  fill: false   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
