name: flutter_responsive_template
description: Package para desenvolvimento de aplicações responsivas (desktop e mobile). 
version: 1.1.18
homepage: https://github.com/lucas9599/flutter_responsive

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"
module:
    androidX: true     

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter  
  flutter_mobx: ^2.0.6+1
  mobx: ^2.2.1
  flutter_modular: ^6.3.2
  shared_preferences: ^2.2.2
  select_form_field: ^2.2.0
  enhance_stepper: ^0.1.1
  printing: ^5.11.0
  pdf: ^3.10.4
  file_selector: ^1.0.1
  bitsdojo_window: ^0.1.5
  data_table_2: ^2.5.8
  encrypt: ^5.0.3
  date_field: ^3.0.3
  brasil_fields: ^1.14.0
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.2.19  
  image: ^4.1.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.2.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "imagens/icon.png"
  image_path_ios: "imagens/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "imagens/icon.png"
  web:
    generate: true
    image_path: "imagens/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "imagens/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  image: imagens/icon.png
  color: "#fce5de" 
  fill: false   
flutter:

